Code refacor + re-design inference ui
RVC-Project/Retrieval-based-Voice-Conversion-WebUI pull request #1304
Opened 2023-09-21 22:02 UTC by blaise-tk

I have added two sub-tabs within the main infer tab with each section; Individual Inference & Batch Inference. I also added the title to the interface.

*Some translations are missing but I don't know those languages.*

![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/133521603/7f629e58-37e0-4bae-b92c-c815ec611870)
![image](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/133521603/79e54a14-cbd1-4cf7-b055-7689c06dff0a)

2023-09-22 03:03 UTC, fumiama approved these changes

2023-09-22 03:59 UTC, Tps-F requested changes

2023-09-22 03:59 UTC, Tps-F commented on infer-web.py
> +            with gr.TabItem(i18n("Batch")):
The i18n has "批次".

2023-09-22 03:59 UTC, Tps-F commented
It's a small mistake and I'll fix it

2023-09-22 04:05 UTC, Tps-F approved these changes

2023-09-23 04:47 UTC, fumiama approved these changes

2023-09-23 04:47 UTC, merged