Update README & en_US locale file
RVC-Project/Retrieval-based-Voice-Conversion-WebUI pull request #1309
Opened 2023-09-22 09:57 UTC by ricecakey06

# Pull request checklist

- [x] The PR has a proper title. Use [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages). (No more branch-name title please)
- [x] Make sure you are requesting the right branch: `dev`.
- [x] Make sure this is ready to be merged into the relevant branch. Please don't create a PR and let it hang for a few days.
- [x] Ensure all tests are passing.
- [x] Ensure linting is passing.

# PR type

- chore

# Description

- Update README file.
- Update en_US locale file.

2023-09-22 12:22 UTC, Tps-F requested changes
Conflict has occurred.
Please create a branch based on the dev branch and cherry-pick your commit.

2023-09-23 04:50 UTC, fumiama approved these changes

2023-09-23 04:52 UTC, fumiama commented
I have fixed the conflicts.

2023-09-23 04:54 UTC, fumiama approved these changes

2023-09-23 06:38 UTC, Tps-F approved these changes

2023-09-23 06:38 UTC, merged