Add standalone inference code
RVC-Project/Retrieval-based-Voice-Conversion-WebUI pull request #1787
Opened 2024-02-01 18:37 UTC by pedrohlopes

# PR type

- new feature

# Description

Adding a simple workflow for standalone pythonic inference: Audio np.array as input and audio np.array as output, with easy to change parameters. Also possibilitates file-to-file workflow. This should allow people to plug RVC inference into their own python codebases without much pain.  
A small addition with no impact to current code as a new VC pipeline syntax is created apart from the original one. Up to date with the current dev branch.

2024-02-04 07:51 UTC, Tps-F requested changes
Almost looks like infer-cli.py
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/tools/infer_cli.py

2024-02-04 07:51 UTC, Tps-F commented on config.py
It is not used anywhere.

2024-02-04 07:51 UTC, Tps-F commented on configs/config.py
You're destroying the config you use elsewhere.

2024-02-04 07:51 UTC, Tps-F commented on configs/config.py
> +    def __init__(self,device='cuda:0',is_half=True, cli_inference=True):
Why do you need to set up here?
At least cli_inference should be False

2024-02-04 07:51 UTC, Tps-F commented on infer/modules/vc/standalone_infer.py
Don't create similar files

2024-02-05 11:37 UTC, pedrohlopes commented on config.py
right... was a leftover code from first implementation I did. My mistake.

2024-03-01 09:39 UTC, closed without merging