Better fp16 detection
RVC-Project/Retrieval-based-Voice-Conversion-WebUI pull request #832
Opened 2023-07-23 03:19 UTC by kalomaze

2023-07-23 03:31 UTC, alexlnkp approved these changes
gogogo

2023-07-23 03:54 UTC, fumiama requested changes
I think you can change the behavior of `device_config` instead of `use_fp32_config`. You can see that that function just determining whether to use fp16 by gpu's name.

2023-07-23 03:54 UTC, fumiama commented on config.py
> +                use_fp32_config()
The function name is still `use_fp32_config` so you might want to change its name to `use_fp16_config` for example.

2023-07-26 03:45 UTC, RVC-Boss commented
I have fixed it. I will temporarily close this PR for now.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/811

2023-07-26 03:45 UTC, closed without merging